security:
    providers:
        in_memory:
            memory: 
              users:
                test:
                    password: testpass
                    roles: 'ROLE_USER'
                admin:
                    password: qwe123
                    roles: 'ROLE_ADMIN'
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false
        default:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                always_use_default_target_path: true
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user,  roles: ROLE_USER }

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER